networks:
  practice-lab:
    driver: bridge
    name: practice-lab
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: query-builder-lab
    ports:
      - '3000:3001'
    networks:
      - practice-lab
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes:
      - .:/app
      - /app/node_modules
